name: Deployment using AWS Elastic Beanstalk with CI/CD

on:
  push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image of our application
        run: |
          docker build -t healthcheck-app:latest -f ./Dockerfile .

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Push Docker image to AWS ECR
        run: |
          docker tag healthcheck-app:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/dbbsoftware-test-task-ecr-repository
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/dbbsoftware-test-task-ecr-repository

      - name: Prepare Dockerrun.aws.json file
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/healthcheck-app:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "5000"
              }
            ]
          }' > Dockerrun.aws.json

      - name: Create deployment package
        run: zip -r deploy.zip Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        run: |
          APPLICATION=$(aws elasticbeanstalk describe-applications --application-names healthcheck-app --query 'Applications[*]' --output text)
          if [ -z "$APPLICATION" ]; then
            echo "Application does not exist. Creating application."
            aws elasticbeanstalk create-application --application-name healthcheck-app
          fi

          echo "Creating application version."
          aws elasticbeanstalk create-application-version \
            --application-name healthcheck-app \
            --version-label v1 \
            --source-bundle S3Bucket=${{ env.AWS_ACCOUNT_ID }},S3Key=deploy.zip

          ENVIRONMENT=$(aws elasticbeanstalk describe-environments --environment-names production --query 'Environments[*]' --output text)
          if [ -z "$ENVIRONMENT" ]; then
            echo "Environment does not exist. Creating environment with application version."
            aws elasticbeanstalk create-environment \
              --application-name healthcheck-app \
              --version-label v1 \
              --environment-name production \
              --solution-stack-name "64bit Amazon Linux 2 v3.3.13 running Docker"
          else
            echo "Environment exists. Updating environment with application version."
            aws elasticbeanstalk update-environment \
              --application-name healthcheck-app \
              --environment-name production \
              --version-label v1
          fi
